/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue';

export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AXBubble: typeof import('ant-design-x-vue')['Bubble']
    AXConversations: typeof import('ant-design-x-vue')['Conversations']
    AXSender: typeof import('ant-design-x-vue')['Sender']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

// For TSX support
declare global {
  const AXBubble: (typeof import('ant-design-x-vue'))['Bubble'];
  const AXConversations: (typeof import('ant-design-x-vue'))['Conversations'];
  const AXSender: (typeof import('ant-design-x-vue'))['Sender'];
  const RouterLink: (typeof import('vue-router'))['RouterLink'];
  const RouterView: (typeof import('vue-router'))['RouterView'];
}
